default: &default
  adapter: postgresql
  encoding: unicode
  # override with ENV['DATABASE_URL']
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: test
